#!/bin/zsh

set -x
entries="English\nSpanish"

selected=$(print $entries|wofi --style /home/carl/.config/wofi/src/mocha/style.css --width 100 --height 200 --dmenu)
selected=${selected:l}

case $selected in
  english)
  exec hyprctl keyword input:kb_layout  us;;
  spanish)
  exec hyprctl keyword input:kb_layout  es;;
esac